# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 9 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is marked as stale because there has been no activity for 60 days. Remove stale label or add new comments or this issue will be closed in 90 day.'
        close-issue-message: 'Close this stale issue.'
        stale-issue-label: 'stale-issue'
        exempt-issue-labels: 'RoadMap,Roadmap'
        days-before-stale: 60
        days-before-close: 30

        stale-pr-message: 'This PR is marked as stale because there has been no activity for 60 days. Remove stale label or add new comments or this PR will be closed in 30 days.'
        close-pr-message: 'Close this stale PR.'
        stale-pr-label: 'stale-pr'
        days-before-pr-stale: 60
        days-before-pr-close: 30
